# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/fabiodelia/Dropbox/Studium CSE/Statistische Physik und Computer Simulation/mdatom/sources"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/fabiodelia/Dropbox/Studium CSE/Statistische Physik und Computer Simulation/mdatom/sources"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/fabiodelia/Dropbox/Studium CSE/Statistische Physik und Computer Simulation/mdatom/sources/CMakeFiles" "/Users/fabiodelia/Dropbox/Studium CSE/Statistische Physik und Computer Simulation/mdatom/sources/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/fabiodelia/Dropbox/Studium CSE/Statistische Physik und Computer Simulation/mdatom/sources/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mdatom

# Build rule for target.
mdatom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mdatom
.PHONY : mdatom

# fast build rule for target.
mdatom/fast:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/build
.PHONY : mdatom/fast

src/auxiliary.o: src/auxiliary.cpp.o
.PHONY : src/auxiliary.o

# target to build an object file
src/auxiliary.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/auxiliary.cpp.o
.PHONY : src/auxiliary.cpp.o

src/auxiliary.i: src/auxiliary.cpp.i
.PHONY : src/auxiliary.i

# target to preprocess a source file
src/auxiliary.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/auxiliary.cpp.i
.PHONY : src/auxiliary.cpp.i

src/auxiliary.s: src/auxiliary.cpp.s
.PHONY : src/auxiliary.s

# target to generate assembly for a file
src/auxiliary.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/auxiliary.cpp.s
.PHONY : src/auxiliary.cpp.s

src/cenma.o: src/cenma.cpp.o
.PHONY : src/cenma.o

# target to build an object file
src/cenma.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/cenma.cpp.o
.PHONY : src/cenma.cpp.o

src/cenma.i: src/cenma.cpp.i
.PHONY : src/cenma.i

# target to preprocess a source file
src/cenma.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/cenma.cpp.i
.PHONY : src/cenma.cpp.i

src/cenma.s: src/cenma.cpp.s
.PHONY : src/cenma.s

# target to generate assembly for a file
src/cenma.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/cenma.cpp.s
.PHONY : src/cenma.cpp.s

src/confa.o: src/confa.cpp.o
.PHONY : src/confa.o

# target to build an object file
src/confa.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/confa.cpp.o
.PHONY : src/confa.cpp.o

src/confa.i: src/confa.cpp.i
.PHONY : src/confa.i

# target to preprocess a source file
src/confa.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/confa.cpp.i
.PHONY : src/confa.cpp.i

src/confa.s: src/confa.cpp.s
.PHONY : src/confa.s

# target to generate assembly for a file
src/confa.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/confa.cpp.s
.PHONY : src/confa.cpp.s

src/forcea.o: src/forcea.cpp.o
.PHONY : src/forcea.o

# target to build an object file
src/forcea.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/forcea.cpp.o
.PHONY : src/forcea.cpp.o

src/forcea.i: src/forcea.cpp.i
.PHONY : src/forcea.i

# target to preprocess a source file
src/forcea.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/forcea.cpp.i
.PHONY : src/forcea.cpp.i

src/forcea.s: src/forcea.cpp.s
.PHONY : src/forcea.s

# target to generate assembly for a file
src/forcea.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/forcea.cpp.s
.PHONY : src/forcea.cpp.s

src/gauss.o: src/gauss.cpp.o
.PHONY : src/gauss.o

# target to build an object file
src/gauss.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/gauss.cpp.o
.PHONY : src/gauss.cpp.o

src/gauss.i: src/gauss.cpp.i
.PHONY : src/gauss.i

# target to preprocess a source file
src/gauss.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/gauss.cpp.i
.PHONY : src/gauss.cpp.i

src/gauss.s: src/gauss.cpp.s
.PHONY : src/gauss.s

# target to generate assembly for a file
src/gauss.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/gauss.cpp.s
.PHONY : src/gauss.cpp.s

src/langevin.o: src/langevin.cpp.o
.PHONY : src/langevin.o

# target to build an object file
src/langevin.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/langevin.cpp.o
.PHONY : src/langevin.cpp.o

src/langevin.i: src/langevin.cpp.i
.PHONY : src/langevin.i

# target to preprocess a source file
src/langevin.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/langevin.cpp.i
.PHONY : src/langevin.cpp.i

src/langevin.s: src/langevin.cpp.s
.PHONY : src/langevin.s

# target to generate assembly for a file
src/langevin.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/langevin.cpp.s
.PHONY : src/langevin.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/packa.o: src/packa.cpp.o
.PHONY : src/packa.o

# target to build an object file
src/packa.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/packa.cpp.o
.PHONY : src/packa.cpp.o

src/packa.i: src/packa.cpp.i
.PHONY : src/packa.i

# target to preprocess a source file
src/packa.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/packa.cpp.i
.PHONY : src/packa.cpp.i

src/packa.s: src/packa.cpp.s
.PHONY : src/packa.s

# target to generate assembly for a file
src/packa.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/packa.cpp.s
.PHONY : src/packa.cpp.s

src/random.o: src/random.cpp.o
.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/runmda.o: src/runmda.cpp.o
.PHONY : src/runmda.o

# target to build an object file
src/runmda.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/runmda.cpp.o
.PHONY : src/runmda.cpp.o

src/runmda.i: src/runmda.cpp.i
.PHONY : src/runmda.i

# target to preprocess a source file
src/runmda.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/runmda.cpp.i
.PHONY : src/runmda.cpp.i

src/runmda.s: src/runmda.cpp.s
.PHONY : src/runmda.s

# target to generate assembly for a file
src/runmda.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/runmda.cpp.s
.PHONY : src/runmda.cpp.s

src/shia.o: src/shia.cpp.o
.PHONY : src/shia.o

# target to build an object file
src/shia.cpp.o:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/shia.cpp.o
.PHONY : src/shia.cpp.o

src/shia.i: src/shia.cpp.i
.PHONY : src/shia.i

# target to preprocess a source file
src/shia.cpp.i:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/shia.cpp.i
.PHONY : src/shia.cpp.i

src/shia.s: src/shia.cpp.s
.PHONY : src/shia.s

# target to generate assembly for a file
src/shia.cpp.s:
	$(MAKE) -f CMakeFiles/mdatom.dir/build.make CMakeFiles/mdatom.dir/src/shia.cpp.s
.PHONY : src/shia.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... mdatom"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/auxiliary.o"
	@echo "... src/auxiliary.i"
	@echo "... src/auxiliary.s"
	@echo "... src/cenma.o"
	@echo "... src/cenma.i"
	@echo "... src/cenma.s"
	@echo "... src/confa.o"
	@echo "... src/confa.i"
	@echo "... src/confa.s"
	@echo "... src/forcea.o"
	@echo "... src/forcea.i"
	@echo "... src/forcea.s"
	@echo "... src/gauss.o"
	@echo "... src/gauss.i"
	@echo "... src/gauss.s"
	@echo "... src/langevin.o"
	@echo "... src/langevin.i"
	@echo "... src/langevin.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/packa.o"
	@echo "... src/packa.i"
	@echo "... src/packa.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/runmda.o"
	@echo "... src/runmda.i"
	@echo "... src/runmda.s"
	@echo "... src/shia.o"
	@echo "... src/shia.i"
	@echo "... src/shia.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

